image: node:16.15.0

pipelines:
  default:
    - step:
        size: 2x
        name: Adsist FrontEnd Redesign
        caches:
          - node
        script:
          - npm ci
          - npm run build:staging
  branches:
    staging:
      - step:
          size: 2x
          name: Build
          caches:
            - node
          script:
            - npm ci
            - npm run build:staging
          artifacts:
            - dist/**
      - step:
          name: Deploy to S3
          deployment: Staging
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.8
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $AWS_S3_BUCKET_FRONTEND_DEV
                ACL: 'public-read'
                LOCAL_PATH: 'dist'
      - step:
          name: Invalidate Cloudfront Cache
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.1.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: $AWS_CLOUDFRONT_DISTRIBUTION_ID_DEV

